### ISSUE TITLE
Reorganize file structure

### ISSUE THREAD

**Issue by rymaju** [Code-4-Community/lucys-love-bus-frontend#30]
Everything under src/components should not be in a folder, removing less files and replacing it with styled components

Files under containers should also be replaced with an index.tsx per container, we need folders still because of ducks (types we use in that container).

**Comment by anirudh723** [comment]
I'll work on this issue. Can we keep the file names for containers with >1 files?

**Comment by rymaju** [comment]
Actually wait on this one because it can create merge conflicts, I want to get the form thing merged in first
